repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        language: system
        description: Detect hardcoded secrets
        pass_filenames: false
        entry: bash -c 'docker run --rm -v "${PWD}:/src" docker.io/zricethezav/gitleaks:latest protect --verbose --redact --staged --source="/src"'